name: Tagging

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-Tag New Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          CARGO_VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          LATEST_TAG=$(git describe --tags --abbrev=0 2> /dev/null || echo "v0.0.0")
          LATEST_VERSION=${LATEST_TAG#v}
          echo "Current Cargo.toml Version: $CARGO_VERSION"
          echo "Latest Tagged Version: $LATEST_TAG ($LATEST_VERSION)"
          if [[ "$CARGO_VERSION" != "$LATEST_VERSION" ]]; then
            echo "::notice title=New Version Detected::Creating and pushing tag v$CARGO_VERSION. This will trigger a new workflow run for the release."
            git tag "v$CARGO_VERSION" -a -m "Release v$CARGO_VERSION"
            REPO_URL="https://${{ secrets.GH_TRIGGER_TOKEN }}@github.com/${{ github.repository }}.git"
            git push "$REPO_URL" "v$CARGO_VERSION"
            exit 0
          else
            echo "Cargo.toml version ($CARGO_VERSION) matches latest tag. Proceeding with build but skipping tag creation."
          fi
